name: testing

on:
  push:
    branches: [ "unit-testing" ]
  pull_request:
    branches: [ "unit-testing" ]

permissions:
  contents: read

jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1']