name: testing

on:
  push:
    branches: [ "unit-testing" ]
  pull_request:
    branches: [ "unit-testing" ]

permissions:
  contents: read

jobs:
  phpunit:
    - uses: actions/checkout@v4

    - name: Run Unit Test
      run: vendor/bin/phpunit tests
      with:
        os: >-
          ['ubuntu-latest', 'windows-latest']
        php: >-
          ['8.1']