name: testing

on:
  push:
    branches: [ "unit-testing" ]
  pull_request:
    branches: [ "unit-testing" ]

permissions:
  contents: read

jobs:
  phpunit:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Run Unit Test
      run: vendor/bin/phpunit tests