name: testing
on:
  push:
    branches: [ "unit-testing" ]
  pull_request:
    branches: [ "unit-testing" ]

jobs:
  phpunit:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.1, 8.2, 8.3]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-php@v4
      with:
        php-version: ${{ matrix.php }}
    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist
    - name: Cache vendor directory
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
        restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-
    - name: Run unit tests
      run: vendor/bin/phpunit tests